// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "portfolio-v2/ui/html"

func About(day string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!-- ============ SLIDE 2 : About ============ --> <section class=\"slide s-orange\" data-slide=\"1\"><div class=\"inner scrollable\"><div class=\"wrap\"><h2 class=\"big\" data-reveal style=\"margin:6px 0 16px\">Who am I?</h2><div class=\"bio-grid\"><div data-reveal><p class=\"lead\" style=\"margin-bottom:14px\">Hi, I am Bitopan Das, a developer with a background in Computer Science. I am from Assam, a state in North East India. I like working with backend stuff (probably because i suck at design, this site is a testament to that).</p><p class=\"lead\">When I am not scratching my head over some code, you can find me playing games, at the gym or just reading some random stuff on the internet.<br>I am currently working as a GET at VOIS.</p></div><div class=\"bio-meta\" data-reveal><div class=\"meta-card\"><div class=\"k\">Languages & Tools</div><div class=\"tags\" style=\"margin-top:18px\"><span class=\"tag\">Go</span> <span class=\"tag\">Python</span> <span class=\"tag\">JavaScript</span> <span class=\"tag\">Node.js</span> <span class=\"tag\">Flutter</span> <span class=\"tag\">AWS</span> <span class=\"tag\">SQL</span> <span class=\"tag\">SAP BTP</span> <span class=\"tag\">SAP UI5</span> <span class=\"tag\">CAPM</span> <span class=\"tag\">Linux</span> <span class=\"tag\">Git</span> <span class=\"tag\">Github</span></div></div></div></div></div></div></section>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = html.Base(day).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
