// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "portfolio-v2/ui/html"

func Experience() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!-- ============ SLIDE 3 : Experience ============ --> <section class=\"slide s-ink\" data-slide=\"2\"><div class=\"inner scrollable\"><div class=\"wrap\"><div style=\"display:flex;justify-content:space-between;align-items:flex-end;gap:14px;flex-wrap:wrap\" data-reveal><div><h2 class=\"big hl-lime\" style=\"margin-top:6px\">Experience</h2></div></div><div class=\"tour-list\" style=\"margin-top:18px\"><div class=\"tour-row\" data-reveal><span class=\"date\">Oct 2026 - Present</span><span class=\"city\">Graduate Engineer Trainee</span><span class=\"venue\">Vodafone India Services Pvt. Ltd.</span></div><div class=\"tour-row\" data-reveal><span class=\"date\">Nov 2025 - Sep 2026</span><span class=\"city\">Developer Trainee</span><span class=\"venue\">Maventic Innovative Solutions Pvt. Ltd.</span></div><div class=\"tour-row\" data-reveal><span class=\"date\">Jun 2025 - Oct 2025</span><span class=\"city\">Development Intern</span><span class=\"venue\">Innect Technologies Pvt. Ltd.</span></div><div class=\"tour-row\" data-reveal><span class=\"date\">Jun 2024 - Jul 2024</span><span class=\"city\">Student Intern</span><span class=\"venue\">Indian Institute of Information Technology Guwahati</span></div></div></div></div></section>s")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = html.Base().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
