// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "portfolio-v2/ui/html"

func Tour() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!-- ============ SLIDE 6 : TOUR ============ --> <section class=\"slide s-ink\" data-slide=\"5\"><div class=\"inner scrollable\"><div class=\"wrap\"><div style=\"display:flex;justify-content:space-between;align-items:flex-end;gap:14px;flex-wrap:wrap\" data-reveal><div><span class=\"kicker hl-orange\">06 / Live</span><h2 class=\"big hl-lime\" style=\"margin-top:6px\">On Tour</h2></div><span class=\"sticker o r3\">2026 Dates</span></div><div class=\"tour-list\" style=\"margin-top:18px\"><div class=\"tour-row\" data-reveal><span class=\"date\">12 Jun 2026</span><span class=\"city\">Bangkok</span><span class=\"venue\">Neon Hall</span><span class=\"status sold\">Sold Out</span></div><div class=\"tour-row\" data-reveal><span class=\"date\">19 Jun 2026</span><span class=\"city\">Singapore</span><span class=\"venue\">Circuit Room</span><span class=\"status on\">On Sale</span></div><div class=\"tour-row\" data-reveal><span class=\"date\">27 Jun 2026</span><span class=\"city\">Tokyo</span><span class=\"venue\">Static Dome</span><span class=\"status on\">On Sale</span></div><div class=\"tour-row\" data-reveal><span class=\"date\">04 Jul 2026</span><span class=\"city\">Seoul</span><span class=\"venue\">Hyper Arena</span><span class=\"status few\">Few Left</span></div><div class=\"tour-row\" data-reveal><span class=\"date\">11 Jul 2026</span><span class=\"city\">Berlin</span><span class=\"venue\">Volt Club</span><span class=\"status sold\">Sold Out</span></div><div class=\"tour-row\" data-reveal><span class=\"date\">18 Jul 2026</span><span class=\"city\">London</span><span class=\"venue\">The Gloss</span><span class=\"status on\">On Sale</span></div></div><p class=\"mono\" data-reveal style=\"margin-top:14px\">More dates dropping all year. Booking inquiries on the contact slide.</p></div></div></section>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = html.Base().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
